version: '3'

services:
  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - api2

  api2:
    build:
      args:
       user: ${USER}
       uid: ${UID}
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: api2
    networks:
      - backend
      - db
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: client_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - database2

  database2:
    image: mariadb
    container_name: database2
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS_ROOT}
      - MYSQL_USER=${USER_DB}
      - MYSQL_PASSWORD=${PASS_DB}
      - MYSQL_DATABASE=${NAME_DB}
    volumes:
      - ./runtime/db:/var/lib/mysql

networks:
  backend:
  db:
